author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /berlin-and-its-environs-handbookberlin-and-its-environs-handbook_EEA653
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: http://readuxout2in.library.emory.edu/books/emory:c4jvr/pages/emory:gktfx/single-page/
image_size:
  page:
    height: 1000
    width: 718
  small-thumbnail:
    height: 100
    width: 71
  thumbnail:
    height: 300
    width: 215
permalink: pretty
publication_info:
  author: Karl Baedeker (Firm)
  date: '2017'
  editors: []
  tei_xml: tei.xml
  title: Berlin and its environs  handbook for travellers , an annotated digital edition
show_annotation_author: true
source_info:
  author: Karl Baedeker (Firm)
  date: '1908'
  pdf_url: http://readuxout2in.library.emory.edu/books/emory:c4jvr/pdf/#page=2
  title: 'Berlin and its environs  handbook for travellers '
  url: http://readuxout2in.library.emory.edu/books/emory:c4jvr/
  via_readux: true
tagline: ', an annotated digital edition'
title: 'Berlin and its environs  handbook for travellers '
url: https://emory-selenium-testing.github.io
version: 0.7
